name = "chinese-name-generator"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
workers_dev = true

# 添加入口点
main = "workers-site/index.js" 