name = "getchinesename"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "if [ -f /bin/bash ]; then bash cloudflare-pages-deploy.sh; else node cloudflare-pages-deploy.js; fi"

[site]
bucket = ".next"

# 限制大文件上传
[site.upload]
format = "directory"
dir = ".next"
include = ["**/*"]
exclude = [
  ".next/cache/**/*",
  "**/*.pack",
  "**/*.pack.gz",
  "**/*.gz"
]

# 禁用文件缓存并指定最大文件大小
[cache]
max_file_size = "10MB"

[env.production]
workers_dev = true 