name = "chinese-name-generator"
main = "workers-site/index.js"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[site]
bucket = ".next"

# 在Cloudflare Pages配置中设置文件排除
# 不要在wrangler.toml中使用site.upload和cache字段

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
workers_dev = false
route = "www.chinese-name-generator.com/*"
zone_id = ""

[env.staging]
name = "chinese-name-generator-staging"
workers_dev = true

[triggers]
crons = [] 