name = "chinese-name-generator"
compatibility_date = "2025-05-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
workers_dev = true

[build.upload]
format = "service-worker" 